import usePacManGame from "../hooks/usePacManGame";
import Board from "../Board/Board";
import styles from "./Game.module.css";

enum Cell {
  Empty,
  Wall,
  Dot,
  PacMan,
  Ghost,
}

enum Direction {
  Up,
  Down,
  Left,
  Right,
}

type GameBoard = Cell[][];

const initialGameBoard: GameBoard = [
  [
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
  ],
  [
    Cell.Wall,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Wall,
  ],
  [
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
  ],
  [
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Ghost,
    Cell.Ghost,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Wall,
  ],
  [
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Ghost,
    Cell.Ghost,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
  ],
  [
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.Dot,
    Cell.Wall,
    Cell.Dot,
    Cell.PacMan,
    Cell.Dot,
    Cell.Wall,
  ],
  [
    Cell.Wall,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Dot,
    Cell.Wall,
  ],
  [
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
    Cell.Wall,
  ],
];

export default function Game() {
  const initialPacManPos = { x: 17, y: 5 };
  const initialGhostPos = { x: 8, y: 3 };

  const { gameBoard, pacManPos, pacManDirection } = usePacManGame(
    initialPacManPos,
    initialGhostPos,
    initialGameBoard
  );
  return (
    <div className={styles.container}>
      <Board board={gameBoard} direction={pacManDirection}></Board>
    </div>
  );
}

export type { GameBoard };
export { Cell, Direction };
